version: '3.8'
services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes: 
      - ./api:/var/www/html
    ports:
      - 8000:80
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ledenbeheer
      MYSQL_DATABASE: ledenbeheer
    volumes:
     - my-db:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  my-db: